shell = "zsh"

[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

[font]

normal.family = "D2CodingLigature Nerd Font"
bold.family = "D2CodingLigature Nerd Font"
italic.family = "D2CodingLigature Nerd Font"
bold_italic.family = "D2CodingLigature Nerd Font"

size = 16.0
